name = "kpark-invent"
main = "src/index.js"
compatibility_date = "2026-08-23"

[assets]
directory = "../frontend"

[vars]
APP_MODE = "live"
APP_VERSION = "3.0.0"

# D1???¬ìš©?????„ë˜ ì£¼ì„???´ì œ?˜ê³  ?¤ì œ database_idë¥??£ìœ¼?¸ìš”.
[[d1_databases]]
binding = "DB"
database_name = "kpark"
database_id = "ddac912c-24f2-4e09-977d-7d41b2b63bcf"
